id = "pico8"
name = "PICO-8"
description = "PICO-8 support."
version = "0.1.0"
schema_version = 1
authors = ["Mario Zoth <mario.zoth@icloud.com>", "Max Brunsfeld <max@zed.dev>"]
repository = "https://github.com/zothynine/zed-pico8"

[language_servers.lua-language-server]
name = "LuaLS"
language = "Lua"

[grammars.lua]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-lua"
# TODO: update to latest commit
commit = "a24dab177e58c9c6832f96b9a73102a0cfbced4a"
